### ISSUE TITLE
Hi May I know what resource you used and how long it takes to get the 128*128?

### ISSUE THREAD

**Issue by kunrenzhilu** [zhangqianhui/progressive_growing_of_gans_tensorflow#2]

**Comment by zhangqianhui** [comment]
I used CelebA dataset, which constains 201599 samples.  Using single k80 gpu, it takes about 4 days.

**Comment by hw654833612** [comment]
Hello! When I run your code, I found that i = 0 can be normal operation, but i = 1 is an error. The following is the wrong content:





pggan.train()
Traceback (most recent call last):

  File "<ipython-input-6-48822d034f0f>", line 1, in <module>
    pggan.train()

  File "Lembert_PGGAN.py", line 126, in train
    opti_D = tf.train.AdamOptimizer(learning_rate=self.learning_rate, beta1=0.0 , beta2=0.99).minimize(self.D_loss, var_list=self.d_vars)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 288, in minimize
    grad_loss=grad_loss)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 354, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 459, in gradients
    (op.name, op.type))

LookupError: No gradient defined for operation 'gradients/discriminator_2/AvgPool_grad/AvgPoolGrad' (op type: AvgPoolGrad)

**Comment by zhangqianhui** [comment]
update your tensorflow version
