### ISSUE TITLE
have a question

### ISSUE THREAD

**Issue by hw654833612** [zhangqianhui/progressive_growing_of_gans_tensorflow#3]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    pggan.build_model_PGGan()
  File "/media/lembert/DCC2B5B2C2B5916E/Windows_Yunpan_Ubuntu/Lembert_AI/example_TF/PG_GANs/zhangqianhui/PGGAN-tensorflow/PGGAN.py", line 36, in build_model_PGGan
    _, self.D_pro_logits = self.discriminate(self.images, reuse=False, pg = self.pg, t=self.trans, alpha_trans=self.alpha_tra)
  File "/media/lembert/DCC2B5B2C2B5916E/Windows_Yunpan_Ubuntu/Lembert_AI/example_TF/PG_GANs/zhangqianhui/PGGAN-tensorflow/PGGAN.py", line 243, in discriminate
    conv = MinibatchstateConcat(conv)
  File "/media/lembert/DCC2B5B2C2B5916E/Windows_Yunpan_Ubuntu/Lembert_AI/example_TF/PG_GANs/zhangqianhui/PGGAN-tensorflow/ops.py", line 153, in MinibatchstateConcat
    vals = tf.tile(vals, multiples=[input.shape[0], 4, 4, 1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3797, in tile
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 494, in apply_op
    raise err
TypeError: Expected binary or unicode string, got Dimension(16)

**Comment by zhangqianhui** [comment]
update your tensorflow to 1.4

**Comment by zhangqianhui** [comment]
or higher version

**Comment by zhangqianhui** [comment]
have your solved this error?

**Comment by hw654833612** [comment]
Yes I have solved this error. But I don’t use MinibatchstateConcat，because It’s not run.




On 01/18/2018 15:06, JiChao Zhang wrote:

have your solved this error?

**Comment by hw654833612** [comment]
Can you add my wechat(huangwei199)? After the exchange can be convenient. I am a PhD student at UESTC.




On 01/18/2018 15:30, Wei Huang wrote:
Yes I have solved this error. But I don’t use MinibatchstateConcat，because It’s not run.




On 01/18/2018 15:06, JiChao Zhang wrote:

have your solved this error?

**Comment by zhangqianhui** [comment]
QQ?

**Comment by hw654833612** [comment]
My qq number is 654833612




On 01/19/2018 15:05, JiChao Zhang wrote:

QQ?
