### ISSUE TITLE
How could we get high-quality images in 1024*1024 format?

### ISSUE THREAD

**Issue by tlatlbtle** [zhangqianhui/progressive_growing_of_gans_tensorflow#6]
I have tried code in [tkarra's implementation](https://github.com/tkarras/progressive_growing_of_gans), however, when I use h5tool.py to generate images, it seems there are some errors in the code.

```
Worker thread caught an exception:

Traceback (most recent call last):

  File "h5tool.py", line 97, in run

    result = func(*args)

  File "h5tool.py", line 146, in task_func

    return process_func(prepared)

  File "h5tool.py", line 569, in process_func

    img = np.pad(np.float32(img), ((pad[1], pad[3]), (pad[0], pad[2]), (0, 0)), 'reflect')

TypeError: float() argument must be a string or a number
```

Have you successfully use high-quality images?

**Comment by zhangqianhui** [comment]
sorry， I don't use the celebA-HQ datasets. But this code can be training is the celebA-HQ datasets. However, needs some changes.
